@ECommerce.Server_HostAddress = https://localhost:7021


###

POST {{ECommerce.Server_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "Username" : "admin",
  "Password": "Password123!"
}

###

POST {{ECommerce.Server_HostAddress}}/api/accounting/reports/balance-sheet
Content-Type: application/json

{
  "asOfDate": "2025-05-24T00:00:00",
  "reportCurrency": "USD",
  "khrtoReportCurrencyExchangeRate": 4150
}

###

POST {{ECommerce.Server_HostAddress}}/api/accounting/reports/simplified-balance-sheet
Content-Type: application/json

{
  "asOfDate": "2025-05-23T00:00:00",
  "reportCurrency": "USD",
  "khrtoReportCurrencyExchangeRate": 4150
}

###
